# Generated by Django 4.0.6 on 2022-08-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='postowner',
        ),
    ]
